name: vin_decoder_service
description: A simple VIN decoding microservice
version: 0.1.1
repository: https://www.github.com/adaptant-labs/vin-decoder-service
issue_tracker: https://www.github.com/adaptant-labs/vin-decoder-service/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  vin_decoder: ^0.1.1
  intl: ^0.16.1
  args: ^1.6.0
  http: ^0.12.1
  async: ^2.4.1
  prometheus_client: ^0.4.0+4
  consul: ^0.0.1

executables:
  vindecoder-service: server
